exiaplayagain_homepage:
    path:     /
    defaults: { _controller: ExiaplayagainBundle:Default:index }

exiaplayagain_login:
    path:     /login
    defaults: { _controller: ExiaplayagainBundle:Account:login }

exiaplayagain_logout:
    path:     /logout
    defaults: { _controller: ExiaplayagainBundle:Account:logout }

exiaplayagain_myaccount:
    path:     /myaccount
    defaults: { _controller: ExiaplayagainBundle:Account:myaccount }

exiaplayagain_userslist:
    path:     /admin/userslist
    defaults: { _controller: ExiaplayagainBundle:Admin:userslist }

exiaplayagain_adduser:
    path:     /admin/adduser
    defaults: { _controller: ExiaplayagainBundle:Admin:adduser }

exiaplayagain_removeuser:
    path:     /admin/removeuser/{username}
    defaults: { _controller: ExiaplayagainBundle:Admin:removeuser }

exiaplayagain_changeisadmin:
    path:     /admin/changeisadmin/{username}
    defaults: { _controller: ExiaplayagainBundle:Admin:changeisadmin }

exiaplayagain_gameslist:
    path:     /admin/gameslist
    defaults: { _controller: ExiaplayagainBundle:Admin:gameslist }

exiaplayagain_addgame:
    path:     /admin/addgame
    defaults: { _controller: ExiaplayagainBundle:Admin:addgame }