exiaplayagain_homepage:
    path:     /
    defaults: { _controller: ExiaplayagainBundle:Default:index }

exiaplayagain_login:
    path:     /login
    defaults: { _controller: ExiaplayagainBundle:Account:login }

exiaplayagain_logout:
    path:     /logout
    defaults: { _controller: ExiaplayagainBundle:Account:logout }

exiaplayagain_myaccount:
    path:     /myaccount
    defaults: { _controller: ExiaplayagainBundle:Account:myaccount }

exiaplayagain_userslist:
    path:     /admin/userslist
    defaults: { _controller: ExiaplayagainBundle:Admin:userslist }

exiaplayagain_adduser:
    path:     /admin/adduser
    defaults: { _controller: ExiaplayagainBundle:Admin:adduser }

exiaplayagain_removeuser:
    path:     /admin/removeuser/{username}
    defaults: { _controller: ExiaplayagainBundle:Admin:removeuser }

exiaplayagain_changeisadmin:
    path:     /admin/changeisadmin/{username}
    defaults: { _controller: ExiaplayagainBundle:Admin:changeisadmin }

exiaplayagain_gameslist:
    path:     /admin/gameslist
    defaults: { _controller: ExiaplayagainBundle:Admin:gameslist }

exiaplayagain_addgame:
    path:     /admin/addgame
    defaults: { _controller: ExiaplayagainBundle:Admin:addgame }

exiaplayagain_editgame:
    path:     /admin/editgame/{gameid}
    defaults: { _controller: ExiaplayagainBundle:Admin:editgame }

exiaplayagain_removegame:
    path:     /admin/removegame/{gameid}
    defaults: { _controller: ExiaplayagainBundle:Admin:removegame }

exiaplayagain_voteslist:
    path:     /admin/voteslist
    defaults: { _controller: ExiaplayagainBundle:Admin:voteslist }

exiaplayagain_addvote:
    path:     /admin/addvote
    defaults: { _controller: ExiaplayagainBundle:Admin:addvote }

exiaplayagain_removevote:
    path:     /admin/removevote/{voteid}
    defaults: { _controller: ExiaplayagainBundle:Admin:removevote }

exiaplayagain_votes:
    path:     /votes
    defaults: { _controller: ExiaplayagainBundle:Default:votes }

exiaplayagain_dovote:
    path:     /dovote/{voteid}
    defaults: { _controller: ExiaplayagainBundle:Default:dovote }

exiaplayagain_games:
    path:     /games
    defaults: { _controller: ExiaplayagainBundle:Default:games }

exiaplayagain_discordbot_home:
    path:    /discordbot/home
    defaults: { _controller: ExiaplayagainBundle:DiscordBot:home }

exiaplayagain_discordbot_sendmessage:
    path:    /discordbot/sendmessage
    defaults: { _controller: ExiaplayagainBundle:DiscordBot:sendmessage }

exiaplayagain_discord_associate:
    path:    /discordbot/associate
    defaults: { _controller: ExiaplayagainBundle:DiscordBot:associate }

exiaplayagain_discord_verify:
    path:    /discordbot/verify/{token}
    defaults: { _controller: ExiaplayagainBundle:DiscordBot:verify }