services:
#    exiaplayagain.example:
#        class: ExiaplayagainBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    exiaplayagain.discordbot:
        class: ExiaplayagainBundle\Services\DiscordBot
        arguments: [@doctrine.orm.entity_manager]